### ISSUE TITLE
Error in high shelf Biquad coefficients?

### ISSUE THREAD

**Issue by MrMormon** [vinniefalco/DSPFilters#27]
From https://forum.juce.com/t/implementing-a-dsp-class-that-contains-includes-and-namespaces-vinne-falco-dspfilters/15684

> Just in case you want to use a high shelf Biquad from DspFilters, I should point out there is an error in the coefficients.
> Vinnie never got around to fixing this, so I run a local branch of my own with the following changes to HighShelf::setup which can be found in [shared\DSPFilters\source\RBJ.cpp](https://github.com/vinniefalco/DSPFilters/blob/master/shared/DSPFilters/source/RBJ.cpp#L159-164), lines 159-164:

> ```
double b0 =    A*( (A+1) + (A-1)*cs + sq );
double b1 = -2*A*( (A-1) + (A+1)*cs );
double b2 =    A*( (A+1) + (A-1)*cs - sq );
double a0 =        (A+1) - (A-1)*cs + sq;
double a1 =    2*( (A-1) - (A+1)*cs );
double a2 =        (A+1) - (A-1)*cs - sq;
```

**Comment by AndrewJJ** [comment]
This is the same as #9 I think

**Comment by MrMormon** [comment]
Way for me to miss it. Now it's fresher I guess?
