### ISSUE TITLE
Errors in RBJ.cpp

### ISSUE THREAD

**Issue by AndrewJJ** [vinniefalco/DSPFilters#9]
I found some subtle errors in the setup for the High Shelf in RBJ.cpp. Funnily enough, it seems to work OK at say 44.1KHz - however it's no good if I oversample by 4x. The issue is some incorrect signs in the coefficient calculations, it should be like this:

    void HighShelf::setup (double sampleRate,
                           double cutoffFrequency,
                           double gainDb,
                           double shelfSlope)
    {
      double A  = pow (10, gainDb/40);
      double w0 = 2 * doublePi * cutoffFrequency / sampleRate;
      double cs = cos (w0);
      double sn = sin (w0);
      double AL = sn / 2 * ::std::sqrt ((A + 1/A) * (1/shelfSlope - 1) + 2);
      double sq = 2 * sqrt(A) * AL;
      double b0 =    A*( (A+1) + (A-1)*cs + sq );
      double b1 = -2*A*( (A-1) + (A+1)*cs );
      double b2 =    A*( (A+1) + (A-1)*cs - sq );
      double a0 =        (A+1) - (A-1)*cs + sq;
      double a1 =    2*( (A-1) - (A+1)*cs );
      double a2 =        (A+1) - (A-1)*cs - sq;
      setCoefficients (a0, a1, a2, b0, b1, b2);
    }

I've verified that this works for me at both normal and oversampled rates.

**Comment by sagamusix** [comment]
Now that @galchinsky has taken over maintenance of the repository, can this fix maybe finally be applied?
There's also a thread about a similar unfixed error in Biquad.cpp on KVR: https://www.kvraudio.com/forum/viewtopic.php?f=33&t=386712

**Comment by galchinsky** [comment]
@sagamusix thanks for reminding me, I missed this because there's no PR. Checking http://www.musicdsp.org/files/Audio-EQ-Cookbook.txt , @AndrewJJ 's solution seems correct so I'll add a patch.
